! Example Template: Simple Pendulum Simulation
! Generated by MechanicsDSL Fortran Backend
!
! This template shows the structure of generated Fortran 90 code.
! Compile with: gfortran -O3 -o pendulum pendulum_template.f90

program simple_pendulum
    implicit none
    
    integer, parameter :: DIM = 2
    real(8) :: y(DIM), dydt(DIM), k1(DIM), k2(DIM), k3(DIM), k4(DIM), tmp(DIM)
    real(8) :: t, dt, t_end
    integer :: i, unit_out, steps
    
    ! Physical Parameters
    real(8), parameter :: m = 1.0d0      ! mass (kg)
    real(8), parameter :: L = 1.0d0      ! length (m)
    real(8), parameter :: g = 9.81d0     ! gravity (m/s²)
    
    ! Initial conditions
    y(1) = 0.5d0    ! θ (angle in rad)
    y(2) = 0.0d0    ! θ̇ (angular velocity in rad/s)
    
    dt = 0.01d0
    t_end = 10.0d0
    t = 0.0d0
    steps = 0
    
    ! Open output file
    unit_out = 20
    open(unit=unit_out, file='pendulum_fortran.csv', status='replace')
    write(unit_out, '(A)') 't,theta,theta_dot'
    
    print *, 'Running simple pendulum simulation...'
    
    ! RK4 integration loop
    do while (t < t_end)
        write(unit_out, '(3(ES14.6,:,","))') t, y(1), y(2)
        
        call equations_of_motion(t, y, k1, L, g)
        tmp = y + 0.5d0 * dt * k1
        call equations_of_motion(t + 0.5d0*dt, tmp, k2, L, g)
        tmp = y + 0.5d0 * dt * k2
        call equations_of_motion(t + 0.5d0*dt, tmp, k3, L, g)
        tmp = y + dt * k3
        call equations_of_motion(t + dt, tmp, k4, L, g)
        
        y = y + dt/6.0d0 * (k1 + 2.0d0*k2 + 2.0d0*k3 + k4)
        t = t + dt
        steps = steps + 1
    end do
    
    close(unit_out)
    print '(A,I6,A)', 'Simulation complete: ', steps, ' steps'
    print '(A,F8.4,A)', 'Final angle: ', y(1), ' rad'
    print *, 'Results saved to pendulum_fortran.csv'
    
contains

    subroutine equations_of_motion(t, y, dydt, L, g)
        real(8), intent(in) :: t, y(DIM), L, g
        real(8), intent(out) :: dydt(DIM)
        real(8) :: theta, theta_dot
        
        ! Unpack state
        theta = y(1)
        theta_dot = y(2)
        
        ! Compute derivatives
        dydt(1) = theta_dot              ! dθ/dt = θ̇
        dydt(2) = -(g/L) * sin(theta)    ! dθ̇/dt = -(g/L)sin(θ)
    end subroutine

end program simple_pendulum
