/**
 * Example Template: Simple Pendulum Simulation
 * Generated by MechanicsDSL JavaScript Backend
 *
 * This template shows the structure of generated JavaScript code.
 * Run with: node javascript_template.js
 * Or use in browser as ES6 module
 */

// Physical Parameters
const m = 1.0;      // mass (kg)
const L = 1.0;      // length (m)
const g = 9.81;     // gravity (m/s²)

const DIM = 2;

/**
 * Equations of motion for simple pendulum
 * @param {number} t - Current time
 * @param {number[]} y - State vector [θ, θ̇]
 * @returns {number[]} - Derivatives [dθ/dt, dθ̇/dt]
 */
function equationsOfMotion(t, y) {
    const theta = y[0];
    const theta_dot = y[1];

    return [
        theta_dot,                    // dθ/dt = θ̇
        -(g / L) * Math.sin(theta)      // dθ̇/dt = -(g/L)sin(θ)
    ];
}

/**
 * Fourth-order Runge-Kutta integration step
 * @param {number} t - Current time
 * @param {number[]} y - State vector
 * @param {number} dt - Time step
 * @returns {number[]} - New state vector
 */
function rk4Step(t, y, dt) {
    const k1 = equationsOfMotion(t, y);
    const k2 = equationsOfMotion(t + 0.5 * dt, y.map((yi, i) => yi + 0.5 * dt * k1[i]));
    const k3 = equationsOfMotion(t + 0.5 * dt, y.map((yi, i) => yi + 0.5 * dt * k2[i]));
    const k4 = equationsOfMotion(t + dt, y.map((yi, i) => yi + dt * k3[i]));

    return y.map((yi, i) => yi + dt / 6 * (k1[i] + 2 * k2[i] + 2 * k3[i] + k4[i]));
}

/**
 * Run simulation
 * @param {Object} options - Simulation options
 * @returns {Object} - Results with t and y arrays
 */
function simulate(options = {}) {
    const {
        theta0 = 0.5,      // initial angle (rad)
        thetaDot0 = 0.0,   // initial angular velocity (rad/s)
        tEnd = 10.0,       // end time (s)
        dt = 0.01          // time step (s)
    } = options;

    let y = [theta0, thetaDot0];
    let t = 0;

    const results = {
        t: [],
        theta: [],
        thetaDot: [],
        x: [],       // Cartesian x
        z: []        // Cartesian z
    };

    while (t < tEnd) {
        results.t.push(t);
        results.theta.push(y[0]);
        results.thetaDot.push(y[1]);
        results.x.push(L * Math.sin(y[0]));
        results.z.push(-L * Math.cos(y[0]));

        y = rk4Step(t, y, dt);
        t += dt;
    }

    return results;
}

/**
 * Convert results to CSV string
 */
function toCSV(results) {
    let csv = 't,theta,theta_dot,x,z\n';
    for (let i = 0; i < results.t.length; i++) {
        csv += `${results.t[i].toFixed(6)},${results.theta[i].toFixed(6)},`;
        csv += `${results.thetaDot[i].toFixed(6)},${results.x[i].toFixed(6)},${results.z[i].toFixed(6)}\n`;
    }
    return csv;
}

// Export for Node.js or ES6 modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { simulate, equationsOfMotion, rk4Step, toCSV };
}

// Run if executed directly in Node.js
if (typeof require !== 'undefined' && require.main === module) {
    console.log('Running simple pendulum simulation...');
    const results = simulate();
    console.log(`Simulation complete: ${results.t.length} points`);
    console.log(`Final angle: ${results.theta[results.theta.length - 1].toFixed(4)} rad`);

    // Save to file
    const fs = require('fs');
    fs.writeFileSync('pendulum_javascript.csv', toCSV(results));
    console.log('Results saved to pendulum_javascript.csv');
}
