#=
Example Template: Simple Pendulum Simulation
Generated by MechanicsDSL Julia Backend

This template shows the structure of generated Julia code.
Run with: julia pendulum_template.jl
Requires: DifferentialEquations.jl, Plots.jl
=#

using DifferentialEquations
using Plots

# Physical Parameters
const m = 1.0      # mass (kg)
const L = 1.0      # length (m)
const g = 9.81     # gravity (m/s²)

"""
    equations_of_motion!(du, u, p, t)

Compute derivatives for simple pendulum.
State: u[1] = θ (angle), u[2] = θ̇ (angular velocity)
"""
function equations_of_motion!(du, u, p, t)
    θ = u[1]
    θ_dot = u[2]
    
    du[1] = θ_dot                    # dθ/dt = θ̇
    du[2] = -(g/L) * sin(θ)          # dθ̇/dt = -(g/L)sin(θ)
end

function simulate(tspan=(0.0, 10.0); θ₀=0.5, θ̇₀=0.0)
    u0 = [θ₀, θ̇₀]
    prob = ODEProblem(equations_of_motion!, u0, tspan)
    sol = solve(prob, Tsit5(), saveat=0.01)
    return sol
end

function plot_results(sol)
    # Convert to Cartesian for visualization
    x = L .* sin.(sol[1, :])
    y = -L .* cos.(sol[1, :])
    
    p1 = plot(sol.t, sol[1, :], 
              label="θ (rad)", 
              xlabel="Time (s)", 
              ylabel="Angle",
              linewidth=2)
    
    p2 = plot(sol.t, sol[2, :], 
              label="θ̇ (rad/s)", 
              xlabel="Time (s)", 
              ylabel="Angular Velocity",
              linewidth=2,
              color=:red)
    
    p3 = plot(x, y, 
              label="Trajectory",
              xlabel="x (m)",
              ylabel="y (m)",
              aspect_ratio=:equal,
              linewidth=2,
              color=:green)
    
    plot(p1, p2, p3, layout=(1, 3), size=(1200, 400), title="Simple Pendulum")
end

# Run simulation
println("Running simple pendulum simulation...")
sol = simulate()
println("Simulation complete: $(length(sol.t)) points")
println("Final angle: $(sol[1, end]) rad")

plot_results(sol)
savefig("pendulum_julia.png")
println("Plot saved to pendulum_julia.png")
