%% Example Template: Simple Pendulum Simulation
%% Generated by MechanicsDSL MATLAB/Octave Backend
%%
%% This template shows the structure of generated MATLAB code.
%% Compatible with MATLAB and GNU Octave

clear; clc; close all;

%% Physical Parameters
global m L g
m = 1.0;      % mass (kg)
L = 1.0;      % length (m)
g = 9.81;     % gravity (m/s²)

%% Initial conditions
% State: [θ, θ̇] - angle and angular velocity
theta_0 = 0.5;      % initial angle (rad)
theta_dot_0 = 0.0;  % initial angular velocity (rad/s)
y0 = [theta_0; theta_dot_0];

tspan = [0 10];

%% Solve ODE using ode45 (Runge-Kutta 4/5)
[t, y] = ode45(@equations_of_motion, tspan, y0);

%% Extract results
theta = y(:, 1);
theta_dot = y(:, 2);

%% Convert to Cartesian coordinates
x = L * sin(theta);
z = -L * cos(theta);

%% Plot results
figure('Position', [100 100 1200 400]);

subplot(1, 3, 1);
plot(t, theta, 'b-', 'LineWidth', 2);
xlabel('Time (s)');
ylabel('Angle (rad)');
title('Pendulum Angle');
grid on;

subplot(1, 3, 2);
plot(t, theta_dot, 'r-', 'LineWidth', 2);
xlabel('Time (s)');
ylabel('Angular Velocity (rad/s)');
title('Angular Velocity');
grid on;

subplot(1, 3, 3);
plot(x, z, 'g-', 'LineWidth', 2);
xlabel('x (m)');
ylabel('y (m)');
title('Pendulum Trajectory');
axis equal;
grid on;

sgtitle('Simple Pendulum Simulation');
saveas(gcf, 'pendulum_matlab.png');

fprintf('Simulation complete: %d points\n', length(t));
fprintf('Final angle: %.4f rad\n', theta(end));

%% Equations of motion function
function dydt = equations_of_motion(t, y)
    global m L g
    
    dydt = zeros(2, 1);
    
    % Unpack state
    theta = y(1);
    theta_dot = y(2);
    
    % Compute derivatives
    dydt(1) = theta_dot;              % dθ/dt = θ̇
    dydt(2) = -(g/L) * sin(theta);    % dθ̇/dt = -(g/L)sin(θ)
end
