//! Example Template: Simple Pendulum Simulation
//! Generated by MechanicsDSL Rust Backend
//!
//! This template shows the structure of generated Rust code.
//! Build with: cargo build --release
//! 
//! Cargo.toml dependencies:
//!   [dependencies]
//!   # Optional: ode_solvers = "0.4"

use std::f64::consts::PI;
use std::fs::File;
use std::io::Write;

// Physical Parameters
const M: f64 = 1.0;      // mass (kg)
const L: f64 = 1.0;      // length (m)
const G: f64 = 9.81;     // gravity (m/s²)

const DIM: usize = 2;

/// Compute derivatives for simple pendulum
/// State: y[0] = θ (angle), y[1] = θ̇ (angular velocity)
fn equations_of_motion(_t: f64, y: &[f64; DIM], dydt: &mut [f64; DIM]) {
    let theta = y[0];
    let theta_dot = y[1];
    
    dydt[0] = theta_dot;                    // dθ/dt = θ̇
    dydt[1] = -(G/L) * theta.sin();         // dθ̇/dt = -(g/L)sin(θ)
}

/// Fourth-order Runge-Kutta integration step
fn rk4_step(t: f64, y: &mut [f64; DIM], dt: f64) {
    let mut k1 = [0.0f64; DIM];
    let mut k2 = [0.0f64; DIM];
    let mut k3 = [0.0f64; DIM];
    let mut k4 = [0.0f64; DIM];
    let mut tmp = [0.0f64; DIM];
    
    equations_of_motion(t, y, &mut k1);
    
    for i in 0..DIM {
        tmp[i] = y[i] + 0.5 * dt * k1[i];
    }
    equations_of_motion(t + 0.5 * dt, &tmp, &mut k2);
    
    for i in 0..DIM {
        tmp[i] = y[i] + 0.5 * dt * k2[i];
    }
    equations_of_motion(t + 0.5 * dt, &tmp, &mut k3);
    
    for i in 0..DIM {
        tmp[i] = y[i] + dt * k3[i];
    }
    equations_of_motion(t + dt, &tmp, &mut k4);
    
    for i in 0..DIM {
        y[i] += dt / 6.0 * (k1[i] + 2.0 * k2[i] + 2.0 * k3[i] + k4[i]);
    }
}

fn main() {
    println!("Running simple pendulum simulation...");
    
    // Initial conditions: θ = 0.5 rad, θ̇ = 0
    let mut y: [f64; DIM] = [0.5, 0.0];
    let dt = 0.01;
    let t_end = 10.0;
    let mut t = 0.0;
    let mut steps = 0;
    
    // Open output file
    let mut file = File::create("pendulum_rust.csv").expect("Cannot create file");
    writeln!(file, "t,theta,theta_dot").unwrap();
    
    // Integration loop
    while t < t_end {
        writeln!(file, "{:.6},{:.6},{:.6}", t, y[0], y[1]).unwrap();
        rk4_step(t, &mut y, dt);
        t += dt;
        steps += 1;
    }
    
    println!("Simulation complete: {} steps", steps);
    println!("Final angle: {:.4} rad", y[0]);
    println!("Results saved to pendulum_rust.csv");
}
