{% set name = "mechanicsdsl-core" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: <UPDATE_WITH_ACTUAL_HASH>

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<3.14
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python >=3.9,<3.14
    - numpy >=1.20.0
    - scipy >=1.7.0
    - sympy >=1.8
    - matplotlib-base >=3.4.0
    - pandas >=1.3.0  # For data export features

test:
  imports:
    - mechanics_dsl
    - mechanics_dsl.compiler
    - mechanics_dsl.parser
    - mechanics_dsl.solver
    - mechanics_dsl.exceptions
  requires:
    - pytest
    - hypothesis
  commands:
    - python -c "from mechanics_dsl import PhysicsCompiler, __version__; print(f'MechanicsDSL v{__version__}')"
    - python -c "from mechanics_dsl import MechanicsDSLError; print('Exception classes available')"

about:
  home: https://github.com/MechanicsDSL/mechanicsdsl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Domain-Specific Language and Transpiler for Classical Mechanics
  description: |
    MechanicsDSL is a computational physics framework that lets you define 
    physical systems in a natural, LaTeX-inspired syntax and automatically 
    generates high-performance simulations. From pendulums to planetary orbits, 
    from Lagrangian mechanics to fluid dynamics—describe it once, simulate it anywhere.
    
    Features:
    - Natural LaTeX-like syntax for physics
    - Automatic derivation of equations of motion
    - Lagrangian and Hamiltonian mechanics
    - Code generation (C++, WASM, Python)
    - SPH fluid dynamics
    - Comprehensive visualization
  doc_url: https://mechanicsdsl.readthedocs.io/
  dev_url: https://github.com/MechanicsDSL/mechanicsdsl

extra:
  recipe-maintainers:
    - MechanicsDSL
