"""
Library-independent ground truth for the planar N-link pendulum chain.

WHY THIS EXISTS
---------------
The suite already has an oracle in `groundtruth.py`, built on
`sympy.physics.mechanics.LagrangesMethod`. That is a genuinely separate
derivation path from MechanicsDSL, and it is adequate for adjudicating
MechanicsDSL. It is NOT adequate once SymPy itself becomes one of the engines
under test: a hand-rolled SymPy derivation checked against SymPy's own
`LagrangesMethod` shares `diff`, `simplify`, `solve`, and the assumptions
machinery beneath them. Agreement under those conditions is closer to a
self-consistency check than to independent confirmation, and it would leave the
three columns of the comparison table resting on evidence of different
strengths -- the one defect a comparison table cannot survive.

This module derives the same equations of motion with NO symbolic algebra at
all. It shares no library with any engine under test; it needs only numpy for
linear algebra. It is therefore a valid referee for all three columns.

It also closes a coverage gap. The symbolic oracle only applies to the
unconstrained Lagrangian pathway, leaving 33 of the suite's 55 cases (60%) with
no independent derivation check. Because this reference produces accelerations
directly from the state, it adjudicates any pathway that can be asked for an
acceleration -- including the Hamiltonian one.

THE DERIVATION
--------------
The suite's `n_pendulum_dsl(N)` builds N point masses, each of mass m, joined
by massless rods of length l, all angles measured from the downward vertical.
Its Lagrangian is

    T = 1/2 * sum_{j,k} a_jk * cos(th_j - th_k) * w_j * w_k
    V = sum_j (N - j) * m * g * l * (1 - cos th_j)

    where a_jk = (N - max(j, k)) * m * l**2      and  w = dth/dt

so the mass matrix is read off directly:

    M_ij(th) = a_ij * cos(th_i - th_j)                                   (1)

For a Lagrangian of the form L = 1/2 w^T M(th) w - V(th), Euler-Lagrange gives

    sum_j M_ij a_j + sum_jk [ dM_ij/dth_k - 1/2 dM_jk/dth_i ] w_j w_k
                                                       + dV/dth_i = 0

Substituting (1) and using dM_ij/dth_k = -a_ij sin(th_i - th_j) (d_ik - d_jk),
the bracketed double sum collapses -- the cross terms cancel exactly -- to a
single sum of squared velocities:

    C_i(th, w) = sum_j a_ij * sin(th_i - th_j) * w_j**2                  (2)

This cancellation is the reason the N-link chain has a closed form worth
writing by hand, and it is verified numerically in `_test_coriolis_identity`
against a finite-difference evaluation of the raw Euler-Lagrange expression,
so the algebra above is checked rather than trusted.

Gravity is immediate:

    G_i(th) = (N - i) * m * g * l * sin(th_i)                            (3)

and the equation of motion is

    M(th) a + C(th, w) + G(th) = 0   =>   a = -M(th)^{-1} (C + G)        (4)

STATE LAYOUT
------------
[th_0, w_0, th_1, w_1, ...] -- interleaved, matching what MechanicsDSL's solver
and `worker.py` already use, so no reordering is needed at the call site.

VALIDATION
----------
Run this file directly to execute the self-tests:

    python reference.py

They check, in order: the N=1 simple pendulum against its analytic form; the
N=2 case against an independently hand-written double pendulum; the Coriolis
identity (2) against finite differences of the Lagrangian; small-oscillation
frequencies against the eigenvalues of the linearised system; and energy
conservation under integration.
"""

from __future__ import annotations

import math
from typing import Optional

import numpy as np

__all__ = ["NLinkChain", "chain_for_case"]


class NLinkChain:
    """Planar N-link pendulum: point masses, massless rods, equal m and l.

    Matches the system generated by `systems.n_pendulum_dsl(N)`.
    """

    def __init__(self, N: int, m: float = 1.0, l: float = 1.0,
                 g: float = 9.81) -> None:
        if N < 1:
            raise ValueError(f"N must be >= 1, got {N}")
        self.N = int(N)
        self.m = float(m)
        self.l = float(l)
        self.g = float(g)

        # a_ij = (N - max(i,j)) * m * l^2. Constant in time, so build it once.
        idx = np.arange(self.N)
        self._a = (self.N - np.maximum.outer(idx, idx)) * self.m * self.l ** 2

        # Gravity coefficient (N - i) * m * g * l, likewise constant.
        self._gcoef = (self.N - idx) * self.m * self.g * self.l

    # -- pieces of the equation of motion -----------------------------------

    def mass_matrix(self, th: np.ndarray) -> np.ndarray:
        """M_ij = a_ij cos(th_i - th_j).  Symmetric, positive definite."""
        th = np.asarray(th, dtype=float)
        return self._a * np.cos(th[:, None] - th[None, :])

    def coriolis(self, th: np.ndarray, w: np.ndarray) -> np.ndarray:
        """C_i = sum_j a_ij sin(th_i - th_j) w_j^2.   See identity (2)."""
        th = np.asarray(th, dtype=float)
        w = np.asarray(w, dtype=float)
        return (self._a * np.sin(th[:, None] - th[None, :])) @ (w ** 2)

    def gravity(self, th: np.ndarray) -> np.ndarray:
        """G_i = (N - i) m g l sin(th_i)."""
        return self._gcoef * np.sin(np.asarray(th, dtype=float))

    # -- the oracle interface ------------------------------------------------

    def accel(self, state: np.ndarray) -> np.ndarray:
        """Angular accelerations at an interleaved state [th0, w0, th1, w1, ...].

        Solves M a = -(C + G) numerically. The mass matrix is never inverted
        symbolically -- that is precisely the step that blows up in the engines
        under test, and doing it here would import their scaling problem into
        the referee.
        """
        th, w = self.split(state)
        M = self.mass_matrix(th)
        rhs = -(self.coriolis(th, w) + self.gravity(th))
        try:
            return np.linalg.solve(M, rhs)
        except np.linalg.LinAlgError:
            # Genuinely singular M. Report rather than silently least-squares
            # it -- substituting a well-defined answer to a different question
            # is the exact failure mode this study measures.
            raise SingularMassMatrix(
                f"mass matrix singular at th={th.tolist()}; "
                f"cond={np.linalg.cond(M):.3e}"
            ) from None

    def rhs(self, _t: float, state: np.ndarray) -> np.ndarray:
        """ODE right-hand side, for handing to an integrator."""
        th, w = self.split(state)
        a = self.accel(state)
        out = np.empty(2 * self.N, dtype=float)
        out[0::2] = w
        out[1::2] = a
        return out

    # -- diagnostics ---------------------------------------------------------

    def energy(self, state: np.ndarray) -> float:
        """Total energy T + V. Conserved for this system; an oracle in itself."""
        th, w = self.split(state)
        T = 0.5 * float(w @ self.mass_matrix(th) @ w)
        V = float(np.sum(self._gcoef * (1.0 - np.cos(th))))
        return T + V

    def condition_number(self, th: np.ndarray) -> float:
        return float(np.linalg.cond(self.mass_matrix(th)))

    def split(self, state: np.ndarray):
        """Interleaved state -> (angles, velocities)."""
        s = np.asarray(state, dtype=float)
        if s.shape != (2 * self.N,):
            raise ValueError(
                f"state must have shape ({2 * self.N},) for N={self.N}, "
                f"got {s.shape}")
        return s[0::2].copy(), s[1::2].copy()

    def default_initial_state(self) -> np.ndarray:
        """The initial conditions `n_pendulum_dsl` writes: th0=0.3, rest 0.15."""
        s = np.zeros(2 * self.N, dtype=float)
        s[0::2] = np.where(np.arange(self.N) == 0, 0.3, 0.15)
        return s

    def __repr__(self) -> str:
        return (f"NLinkChain(N={self.N}, m={self.m}, l={self.l}, g={self.g})")


class SingularMassMatrix(RuntimeError):
    """Raised when M(th) cannot be solved. Loud by design."""


def chain_for_case(case: dict) -> Optional[NLinkChain]:
    """Build a reference for a suite case, or None if this family doesn't apply.

    Only the `dof` axis is the plain equal-parameter N-link chain. The other
    axes perturb masses or add constraints and need their own references (or
    none).
    """
    if case.get("axis") != "dof":
        return None
    return NLinkChain(int(case["knob"]))


# ===========================================================================
# Self-tests. Run: python reference.py
# ===========================================================================

def _test_simple_pendulum() -> None:
    """N=1 must reduce to th'' = -(g/l) sin th."""
    c = NLinkChain(1, m=1.0, l=1.0, g=9.81)
    for th in (0.0, 0.3, 1.0, -0.7, 3.0):
        for w in (0.0, 0.5, -2.0):
            got = c.accel([th, w])[0]
            want = -(c.g / c.l) * math.sin(th)
            assert abs(got - want) < 1e-13, (th, w, got, want)
    print("  [ok] N=1 reduces to the analytic simple pendulum")


def _double_pendulum_reference(th, w, m=1.0, l=1.0, g=9.81):
    """Independently hand-written double pendulum, point masses at both joints.

    Written from the standard textbook form rather than from this module's
    general code, so agreement is a real cross-check rather than a tautology.
    """
    t0, t1 = th
    w0, w1 = w
    d = t0 - t1
    # M for two equal point masses on equal rods:
    #   [ 2 m l^2        m l^2 cos d ]
    #   [ m l^2 cos d    m l^2       ]
    M = np.array([[2.0 * m * l * l, m * l * l * math.cos(d)],
                  [m * l * l * math.cos(d), m * l * l]])
    # Centrifugal terms and gravity, standard form.
    rhs = np.array([
        -m * l * l * math.sin(d) * w1 * w1 - 2.0 * m * g * l * math.sin(t0),
        +m * l * l * math.sin(d) * w0 * w0 - 1.0 * m * g * l * math.sin(t1),
    ])
    return np.linalg.solve(M, rhs)


def _test_double_pendulum() -> None:
    c = NLinkChain(2)
    rng = np.random.default_rng(20260822)
    worst = 0.0
    for _ in range(500):
        th = rng.uniform(-2.5, 2.5, size=2)
        w = rng.uniform(-3.0, 3.0, size=2)
        state = np.empty(4)
        state[0::2], state[1::2] = th, w
        got = c.accel(state)
        want = _double_pendulum_reference(th, w)
        worst = max(worst, float(np.max(np.abs(got - want))))
    assert worst < 1e-11, f"double pendulum mismatch {worst:.3e}"
    print(f"  [ok] N=2 matches a hand-written double pendulum "
          f"(worst {worst:.2e} over 500 random states)")


def _test_coriolis_identity() -> None:
    """Check identity (2) against raw Euler-Lagrange by finite differences.

    This is the step where a derivation error would hide, so it is checked
    numerically rather than trusted. We evaluate

        sum_jk [ dM_ij/dth_k - 1/2 dM_jk/dth_i ] w_j w_k

    with central differences on M, and compare against the closed form.
    """
    rng = np.random.default_rng(7)
    for N in (2, 3, 5):
        c = NLinkChain(N)
        for _ in range(40):
            th = rng.uniform(-2.0, 2.0, size=N)
            w = rng.uniform(-2.0, 2.0, size=N)
            h = 1e-6
            dM = np.zeros((N, N, N))       # dM[i,j,k] = dM_ij / dth_k
            for k in range(N):
                tp, tm = th.copy(), th.copy()
                tp[k] += h
                tm[k] -= h
                dM[:, :, k] = (c.mass_matrix(tp) - c.mass_matrix(tm)) / (2 * h)
            brute = np.zeros(N)
            for i in range(N):
                acc = 0.0
                for j in range(N):
                    for k in range(N):
                        acc += (dM[i, j, k] - 0.5 * dM[j, k, i]) * w[j] * w[k]
                brute[i] = acc
            closed = c.coriolis(th, w)
            err = float(np.max(np.abs(brute - closed)))
            assert err < 1e-5, f"N={N} Coriolis identity failed: {err:.3e}"
    print("  [ok] Coriolis identity (2) matches finite-difference "
          "Euler-Lagrange for N=2,3,5")


def _test_small_oscillation() -> None:
    """Linearised frequencies must match the generalised eigenproblem.

    Near th=0, M -> a and the restoring term -> diag(gcoef), so the squared
    normal-mode frequencies are the eigenvalues of a^{-1} diag(gcoef).
    """
    import scipy.linalg as sla
    for N in (1, 2, 3, 4):
        c = NLinkChain(N)
        M0 = c.mass_matrix(np.zeros(N))
        K0 = np.diag(c._gcoef)
        want = np.sort(np.real(sla.eigvals(K0, M0)))
        # Recover the same thing from finite differences of accel() at rest.
        J = np.zeros((N, N))
        h = 1e-7
        for k in range(N):
            sp_, sm_ = np.zeros(2 * N), np.zeros(2 * N)
            sp_[2 * k] = +h
            sm_[2 * k] = -h
            J[:, k] = (c.accel(sp_) - c.accel(sm_)) / (2 * h)
        got = np.sort(np.real(np.linalg.eigvals(-J)))
        err = float(np.max(np.abs(got - want)))
        assert err < 1e-4, f"N={N} small-oscillation mismatch {err:.3e}"
    print("  [ok] small-oscillation frequencies match the linearised "
          "eigenproblem for N=1..4")


def _test_energy_conservation() -> None:
    """Integrate and confirm energy holds. Independent of the derivation."""
    from scipy.integrate import solve_ivp
    for N in (1, 2, 3):
        c = NLinkChain(N)
        s0 = c.default_initial_state()
        E0 = c.energy(s0)
        sol = solve_ivp(c.rhs, (0.0, 10.0), s0, method="DOP853",
                        rtol=1e-12, atol=1e-12, dense_output=False)
        assert sol.success, sol.message
        drift = max(abs(c.energy(sol.y[:, i]) - E0) / max(abs(E0), 1e-30)
                    for i in range(sol.y.shape[1]))
        assert drift < 1e-9, f"N={N} energy drift {drift:.3e}"
        print(f"  [ok] N={N} conserves energy to {drift:.2e} over 10 s")


def _test_symmetry_and_shape() -> None:
    c = NLinkChain(4)
    th = np.array([0.1, -0.4, 0.9, 0.2])
    M = c.mass_matrix(th)
    assert np.allclose(M, M.T, atol=1e-15), "mass matrix not symmetric"
    ev = np.linalg.eigvalsh(M)
    assert ev.min() > 0, f"mass matrix not positive definite: {ev}"
    print(f"  [ok] mass matrix symmetric and positive definite "
          f"(min eigenvalue {ev.min():.3f})")


def main() -> int:
    print("reference.py self-tests -- planar N-link chain\n")
    _test_simple_pendulum()
    _test_double_pendulum()
    _test_coriolis_identity()
    _test_symmetry_and_shape()
    _test_small_oscillation()
    _test_energy_conservation()
    print("\nAll self-tests passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
